sub-EC2/sub-EC2_ses-EC2-B105.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-EC2/sub-EC2_ses-EC2-B15.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-EC2/sub-EC2_ses-EC2-B76.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-EC2/sub-EC2_ses-EC2-B8.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-EC2/sub-EC2_ses-EC2-B89.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-EC2/sub-EC2_ses-EC2-B9.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-EC9/sub-EC9_ses-EC9-B15.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-EC9/sub-EC9_ses-EC9-B39.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-EC9/sub-EC9_ses-EC9-B46.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-EC9/sub-EC9_ses-EC9-B49.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-EC9/sub-EC9_ses-EC9-B53.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-EC9/sub-EC9_ses-EC9-B60.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-EC9/sub-EC9_ses-EC9-B63.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP31/sub-GP31_ses-GP31-B1.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP31/sub-GP31_ses-GP31-B2.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP31/sub-GP31_ses-GP31-B21.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP31/sub-GP31_ses-GP31-B4.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP31/sub-GP31_ses-GP31-B6.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP31/sub-GP31_ses-GP31-B63.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP31/sub-GP31_ses-GP31-B65.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP31/sub-GP31_ses-GP31-B67.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP31/sub-GP31_ses-GP31-B69.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP31/sub-GP31_ses-GP31-B71.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP31/sub-GP31_ses-GP31-B78.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP31/sub-GP31_ses-GP31-B82.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP31/sub-GP31_ses-GP31-B83.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP31/sub-GP31_ses-GP31-B9.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP33/sub-GP33_ses-GP33-B1.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP33/sub-GP33_ses-GP33-B30.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-GP33/sub-GP33_ses-GP33-B5.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

