sub-anm00314746/sub-anm00314746_ses-20151020T093604.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-anm00314746/sub-anm00314746_ses-20151021T112541.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-anm00314746/sub-anm00314746_ses-20151022T151738.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-anm00314756/sub-anm00314756_ses-20151020T194211.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-anm00314756/sub-anm00314756_ses-20151023T141029.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-anm00314757/sub-anm00314757_ses-20151020T173731.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-anm00314757/sub-anm00314757_ses-20151021T180248.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-anm00314758/sub-anm00314758_ses-20151020T104930.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-anm00314758/sub-anm00314758_ses-20151021T101014.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-anm00314758/sub-anm00314758_ses-20151022T112047.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-anm00314758/sub-anm00314758_ses-20151023T094901.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-anm00314760/sub-anm00314760_ses-20151020T155230.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-anm00314760/sub-anm00314760_ses-20151021T164427.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-anm00314760/sub-anm00314760_ses-20151022T163913.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD12/sub-BAYLORCD12_ses-20180125T191601.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD12/sub-BAYLORCD12_ses-20180126T122506.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD12/sub-BAYLORCD12_ses-20180128T220037.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD12/sub-BAYLORCD12_ses-20180129T160551.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD12/sub-BAYLORCD12_ses-20180130T153224.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD13/sub-BAYLORCD13_ses-20171211T135437.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD13/sub-BAYLORCD13_ses-20171212T131814.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD13/sub-BAYLORCD13_ses-20171213T135007.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD13/sub-BAYLORCD13_ses-20171214T103426.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD13/sub-BAYLORCD13_ses-20171215T133939.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD14/sub-BAYLORCD14_ses-20171024T112103.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD14/sub-BAYLORCD14_ses-20171025T114022.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD14/sub-BAYLORCD14_ses-20171026T150956.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD14/sub-BAYLORCD14_ses-20171027T115804.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD14/sub-BAYLORCD14_ses-20171028T165746.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD6/sub-BAYLORCD6_ses-20170610T135720.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD6/sub-BAYLORCD6_ses-20170611T140007.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD6/sub-BAYLORCD6_ses-20170612T125622.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD6/sub-BAYLORCD6_ses-20170614T111143.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD8/sub-BAYLORCD8_ses-20171016T121417.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD8/sub-BAYLORCD8_ses-20171017T114425.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD8/sub-BAYLORCD8_ses-20171018T123550.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD8/sub-BAYLORCD8_ses-20171019T123347.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORCD8/sub-BAYLORCD8_ses-20171020T124659.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORNL12/sub-BAYLORNL12_ses-20170610T122530.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORNL12/sub-BAYLORNL12_ses-20170611T124136.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORNL12/sub-BAYLORNL12_ses-20170612T115219.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORNL12/sub-BAYLORNL12_ses-20170613T123812.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORNL12/sub-BAYLORNL12_ses-20170614T094441.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORNL14/sub-BAYLORNL14_ses-20170602T114550.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORNL14/sub-BAYLORNL14_ses-20170603T153540.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORNL14/sub-BAYLORNL14_ses-20170604T150059.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORNL14/sub-BAYLORNL14_ses-20170605T123139.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORNL14/sub-BAYLORNL14_ses-20170606T094050.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORNL14/sub-BAYLORNL14_ses-20170607T130355.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORNL15/sub-BAYLORNL15_ses-20170602T095359.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORNL15/sub-BAYLORNL15_ses-20170603T122807.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORNL15/sub-BAYLORNL15_ses-20170604T121032.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORNL15/sub-BAYLORNL15_ses-20170605T093327.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-BAYLORNL15/sub-BAYLORNL15_ses-20170607T094337.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 59, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

