sub-anm369962/sub-anm369962_ses-20170309.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369962/sub-anm369962_ses-20170310.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369962/sub-anm369962_ses-20170313.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369962/sub-anm369962_ses-20170314.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369962/sub-anm369962_ses-20170316.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369962/sub-anm369962_ses-20170317.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369963/sub-anm369963_ses-20170226.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369963/sub-anm369963_ses-20170227.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369963/sub-anm369963_ses-20170228.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369963/sub-anm369963_ses-20170301.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369963/sub-anm369963_ses-20170302.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369963/sub-anm369963_ses-20170306.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369963/sub-anm369963_ses-20170309.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369963/sub-anm369963_ses-20170310.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369964/sub-anm369964_ses-20170320.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369964/sub-anm369964_ses-20170321.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369964/sub-anm369964_ses-20170322.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm369964/sub-anm369964_ses-20170323.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372793/sub-anm372793_ses-20170504.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372793/sub-anm372793_ses-20170508.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372793/sub-anm372793_ses-20170512.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372793/sub-anm372793_ses-20170513.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372793/sub-anm372793_ses-20170514.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372794/sub-anm372794_ses-20170621.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372794/sub-anm372794_ses-20170622.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372794/sub-anm372794_ses-20170624.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372794/sub-anm372794_ses-20170625.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372794/sub-anm372794_ses-20170626.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372794/sub-anm372794_ses-20170627.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372795/sub-anm372795_ses-20170714.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372795/sub-anm372795_ses-20170715.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372795/sub-anm372795_ses-20170716.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372795/sub-anm372795_ses-20170718.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372797/sub-anm372797_ses-20170615.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372797/sub-anm372797_ses-20170617.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372904/sub-anm372904_ses-20170615.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372904/sub-anm372904_ses-20170616.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372904/sub-anm372904_ses-20170617.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372904/sub-anm372904_ses-20170618.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372904/sub-anm372904_ses-20170619.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372905/sub-anm372905_ses-20170715.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372905/sub-anm372905_ses-20170716.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372905/sub-anm372905_ses-20170717.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372906/sub-anm372906_ses-20170608.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372906/sub-anm372906_ses-20170610.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372906/sub-anm372906_ses-20170611.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372906/sub-anm372906_ses-20170612.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372907/sub-anm372907_ses-20170608.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372907/sub-anm372907_ses-20170610.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372907/sub-anm372907_ses-20170612.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372907/sub-anm372907_ses-20170613.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372909/sub-anm372909_ses-20170520.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

sub-anm372909/sub-anm372909_ses-20170522.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 77, in main
    BareAssetMeta(**metadata)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for BareAssetMeta
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Project' (type=value_error.const; given=Session; permitted=('Project',))
wasGeneratedBy -> 0 -> name
  field required (type=value_error.missing)
wasGeneratedBy -> 0 -> schemaKey
  unexpected value; permitted: 'Activity' (type=value_error.const; given=Session; permitted=('Activity',))

