sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-10_slice-20200407-slice-1_cell-20200407-sample-10_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-11_slice-20200407-slice-4_cell-20200407-sample-11_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-12_slice-20200407-slice-4_cell-20200407-sample-12_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-13_slice-20200407-slice-5_cell-20200407-sample-13_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-14_slice-20200407-slice-5_cell-20200407-sample-14_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-15_slice-20200407-slice-5_cell-20200407-sample-15_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-16_slice-20200407-slice-5_cell-20200407-sample-16_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-18_slice-20200407-slice-5_cell-20200407-sample-18_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-19_slice-20200407-slice-5_cell-20200407-sample-19_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-1_slice-20200407-slice-1_cell-20200407-sample-1_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-20_slice-20200407-slice-5_cell-20200407-sample-20_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-21_slice-20200407-slice-5_cell-20200407-sample-21_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-22_slice-20200407-slice-5_cell-20200407-sample-22_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-23_slice-20200407-slice-5_cell-20200407-sample-23_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-24_slice-20200407-slice-5_cell-20200407-sample-24_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-25_slice-20200407-slice-5_cell-20200407-sample-25_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-26_slice-20200407-slice-5_cell-20200407-sample-26_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-2_slice-20200407-slice-1_cell-20200407-sample-2_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-3_slice-20200407-slice-1_cell-20200407-sample-3_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-4_slice-20200407-slice-1_cell-20200407-sample-4_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-5_slice-20200407-slice-1_cell-20200407-sample-5_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-6_slice-20200407-slice-1_cell-20200407-sample-6_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-7_slice-20200407-slice-1_cell-20200407-sample-7_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-8_slice-20200407-slice-1_cell-20200407-sample-8_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-INETJ/sub-mouse-INETJ_ses-20200407-sample-9_slice-20200407-slice-1_cell-20200407-sample-9_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-KIYRP/sub-mouse-KIYRP_ses-20200403-sample-10_slice-20200403-slice-3_cell-20200403-sample-10_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-KIYRP/sub-mouse-KIYRP_ses-20200403-sample-11_slice-20200403-slice-3_cell-20200403-sample-11_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-KIYRP/sub-mouse-KIYRP_ses-20200403-sample-12_slice-20200403-slice-4_cell-20200403-sample-12_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-KIYRP/sub-mouse-KIYRP_ses-20200403-sample-13_slice-20200403-slice-4_cell-20200403-sample-13_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-KIYRP/sub-mouse-KIYRP_ses-20200403-sample-14_slice-20200403-slice-4_cell-20200403-sample-14_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-KIYRP/sub-mouse-KIYRP_ses-20200403-sample-16_slice-20200403-slice-4_cell-20200403-sample-16_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-KIYRP/sub-mouse-KIYRP_ses-20200403-sample-1_slice-20200403-slice-1_cell-20200403-sample-1_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-KIYRP/sub-mouse-KIYRP_ses-20200403-sample-2_slice-20200403-slice-1_cell-20200403-sample-2_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-KIYRP/sub-mouse-KIYRP_ses-20200403-sample-3_slice-20200403-slice-1_cell-20200403-sample-3_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-KIYRP/sub-mouse-KIYRP_ses-20200403-sample-4_slice-20200403-slice-1_cell-20200403-sample-4_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-KIYRP/sub-mouse-KIYRP_ses-20200403-sample-5_slice-20200403-slice-2_cell-20200403-sample-5_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-KIYRP/sub-mouse-KIYRP_ses-20200403-sample-6_slice-20200403-slice-2_cell-20200403-sample-6_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-KIYRP/sub-mouse-KIYRP_ses-20200403-sample-7_slice-20200403-slice-2_cell-20200403-sample-7_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-KIYRP/sub-mouse-KIYRP_ses-20200403-sample-8_slice-20200403-slice-2_cell-20200403-sample-8_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-KIYRP/sub-mouse-KIYRP_ses-20200403-sample-9_slice-20200403-slice-2_cell-20200403-sample-9_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-10_slice-20200410-slice-1_cell-20200410-sample-10_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-11_slice-20200410-slice-1_cell-20200410-sample-11_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-13_slice-20200410-slice-1_cell-20200410-sample-13_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-14_slice-20200410-slice-1_cell-20200410-sample-14_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-15_slice-20200410-slice-1_cell-20200410-sample-15_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-17_slice-20200410-slice-2_cell-20200410-sample-17_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-18_slice-20200410-slice-2_cell-20200410-sample-18_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-1_slice-20200410-slice-1_cell-20200410-sample-1_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-20_slice-20200410-slice-2_cell-20200410-sample-20_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-21_slice-20200410-slice-2_cell-20200410-sample-21_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-22_slice-20200410-slice-2_cell-20200410-sample-22_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-23_slice-20200410-slice-2_cell-20200410-sample-23_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-24_slice-20200410-slice-3_cell-20200410-sample-24_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-26_slice-20200410-slice-3_cell-20200410-sample-26_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-27_slice-20200410-slice-3_cell-20200410-sample-27_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-28_slice-20200410-slice-3_cell-20200410-sample-28_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-29_slice-20200410-slice-3_cell-20200410-sample-29_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-2_slice-20200410-slice-1_cell-20200410-sample-2_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-30_slice-20200410-slice-3_cell-20200410-sample-30_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-4_slice-20200410-slice-1_cell-20200410-sample-4_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-5_slice-20200410-slice-1_cell-20200410-sample-5_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-6_slice-20200410-slice-1_cell-20200410-sample-6_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-7_slice-20200410-slice-1_cell-20200410-sample-7_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-MITSU/sub-mouse-MITSU_ses-20200410-sample-8_slice-20200410-slice-1_cell-20200410-sample-8_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-10_slice-20200409-slice-2_cell-20200409-sample-10_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-11_slice-20200409-slice-2_cell-20200409-sample-11_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-12_slice-20200409-slice-2_cell-20200409-sample-12_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-13_slice-20200409-slice-2_cell-20200409-sample-13_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-14_slice-20200409-slice-2_cell-20200409-sample-14_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-15_slice-20200409-slice-3_cell-20200409-sample-15_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-17_slice-20200409-slice-3_cell-20200409-sample-17_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-18_slice-20200409-slice-4_cell-20200409-sample-18_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-19_slice-20200409-slice-4_cell-20200409-sample-19_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-1_slice-20200409-slice-1_cell-20200409-sample-1_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-20_slice-20200409-slice-4_cell-20200409-sample-20_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-2_slice-20200409-slice-1_cell-20200409-sample-2_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-3_slice-20200409-slice-1_cell-20200409-sample-3_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-4_slice-20200409-slice-1_cell-20200409-sample-4_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-5_slice-20200409-slice-1_cell-20200409-sample-5_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-6_slice-20200409-slice-1_cell-20200409-sample-6_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-7_slice-20200409-slice-1_cell-20200409-sample-7_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-8_slice-20200409-slice-1_cell-20200409-sample-8_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-NDKCQ/sub-mouse-NDKCQ_ses-20200409-sample-9_slice-20200409-slice-1_cell-20200409-sample-9_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-10_slice-20200414-slice-2_cell-20200414-sample-10_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-11_slice-20200414-slice-2_cell-20200414-sample-11_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-12_slice-20200414-slice-3_cell-20200414-sample-12_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-13_slice-20200414-slice-3_cell-20200414-sample-13_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-14_slice-20200414-slice-3_cell-20200414-sample-14_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-15_slice-20200414-slice-3_cell-20200414-sample-15_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-16_slice-20200414-slice-3_cell-20200414-sample-16_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-17_slice-20200414-slice-3_cell-20200414-sample-17_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-18_slice-20200414-slice-3_cell-20200414-sample-18_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-19_slice-20200414-slice-3_cell-20200414-sample-19_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-1_slice-20200414-slice-1_cell-20200414-sample-1_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-21_slice-20200414-slice-3_cell-20200414-sample-21_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-22_slice-20200414-slice-3_cell-20200414-sample-22_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-23_slice-20200414-slice-3_cell-20200414-sample-23_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-24_slice-20200414-slice-3_cell-20200414-sample-24_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-25_slice-20200414-slice-3_cell-20200414-sample-25_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-26_slice-20200414-slice-3_cell-20200414-sample-26_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-27_slice-20200414-slice-3_cell-20200414-sample-27_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-2_slice-20200414-slice-1_cell-20200414-sample-2_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-3_slice-20200414-slice-1_cell-20200414-sample-3_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-4_slice-20200414-slice-1_cell-20200414-sample-4_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-5_slice-20200414-slice-2_cell-20200414-sample-5_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-6_slice-20200414-slice-2_cell-20200414-sample-6_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-7_slice-20200414-slice-2_cell-20200414-sample-7_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-8_slice-20200414-slice-2_cell-20200414-sample-8_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-SCEAC/sub-mouse-SCEAC_ses-20200414-sample-9_slice-20200414-slice-2_cell-20200414-sample-9_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-10_slice-20200413-slice-2_cell-20200413-sample-10_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-11_slice-20200413-slice-2_cell-20200413-sample-11_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-12_slice-20200413-slice-2_cell-20200413-sample-12_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-13_slice-20200413-slice-2_cell-20200413-sample-13_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-14_slice-20200413-slice-2_cell-20200413-sample-14_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-15_slice-20200413-slice-2_cell-20200413-sample-15_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-16_slice-20200413-slice-2_cell-20200413-sample-16_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-17_slice-20200413-slice-2_cell-20200413-sample-17_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-18_slice-20200413-slice-2_cell-20200413-sample-18_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-19_slice-20200413-slice-2_cell-20200413-sample-19_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-1_slice-20200413-slice-1_cell-20200413-sample-1_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-20_slice-20200413-slice-3_cell-20200413-sample-20_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-21_slice-20200413-slice-3_cell-20200413-sample-21_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-22_slice-20200413-slice-3_cell-20200413-sample-22_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-23_slice-20200413-slice-3_cell-20200413-sample-23_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-2_slice-20200413-slice-1_cell-20200413-sample-2_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-3_slice-20200413-slice-1_cell-20200413-sample-3_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-4_slice-20200413-slice-1_cell-20200413-sample-4_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-5_slice-20200413-slice-1_cell-20200413-sample-5_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-6_slice-20200413-slice-1_cell-20200413-sample-6_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-7_slice-20200413-slice-2_cell-20200413-sample-7_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-8_slice-20200413-slice-2_cell-20200413-sample-8_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-UEQOU/sub-mouse-UEQOU_ses-20200413-sample-9_slice-20200413-slice-2_cell-20200413-sample-9_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-10_slice-20200406-slice-3_cell-20200406-sample-10_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-11_slice-20200406-slice-3_cell-20200406-sample-11_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-12_slice-20200406-slice-4_cell-20200406-sample-12_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-13_slice-20200406-slice-4_cell-20200406-sample-13_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-15_slice-20200406-slice-4_cell-20200406-sample-15_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-16_slice-20200406-slice-4_cell-20200406-sample-16_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-17_slice-20200406-slice-4_cell-20200406-sample-17_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-19_slice-20200406-slice-4_cell-20200406-sample-19_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-1_slice-20200406-slice-1_cell-20200406-sample-1_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-20_slice-20200406-slice-4_cell-20200406-sample-20_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-21_slice-20200406-slice-4_cell-20200406-sample-21_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-22_slice-20200406-slice-4_cell-20200406-sample-22_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-23_slice-20200406-slice-4_cell-20200406-sample-23_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-24_slice-20200406-slice-4_cell-20200406-sample-24_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-25_slice-20200406-slice-5_cell-20200406-sample-25_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-27_slice-20200406-slice-5_cell-20200406-sample-27_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-28_slice-20200406-slice-6_cell-20200406-sample-28_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-29_slice-20200406-slice-6_cell-20200406-sample-29_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-2_slice-20200406-slice-1_cell-20200406-sample-2_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-30_slice-20200406-slice-6_cell-20200406-sample-30_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-31_slice-20200406-slice-6_cell-20200406-sample-31_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-32_slice-20200406-slice-6_cell-20200406-sample-32_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-3_slice-20200406-slice-1_cell-20200406-sample-3_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-4_slice-20200406-slice-2_cell-20200406-sample-4_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-5_slice-20200406-slice-2_cell-20200406-sample-5_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-6_slice-20200406-slice-2_cell-20200406-sample-6_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-WPOGH/sub-mouse-WPOGH_ses-20200406-sample-7_slice-20200406-slice-2_cell-20200406-sample-7_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-11_slice-20200408-slice-3_cell-20200408-sample-11_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-12_slice-20200408-slice-3_cell-20200408-sample-12_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-13_slice-20200408-slice-3_cell-20200408-sample-13_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-14_slice-20200408-slice-3_cell-20200408-sample-14_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-15_slice-20200408-slice-3_cell-20200408-sample-15_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-16_slice-20200408-slice-3_cell-20200408-sample-16_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-17_slice-20200408-slice-3_cell-20200408-sample-17_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-18_slice-20200408-slice-4_cell-20200408-sample-18_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-19_slice-20200408-slice-4_cell-20200408-sample-19_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-1_slice-20200408-slice-1_cell-20200408-sample-1_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-20_slice-20200408-slice-4_cell-20200408-sample-20_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-21_slice-20200408-slice-4_cell-20200408-sample-21_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-23_slice-20200408-slice-4_cell-20200408-sample-23_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-24_slice-20200408-slice-4_cell-20200408-sample-24_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-25_slice-20200408-slice-4_cell-20200408-sample-25_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-26_slice-20200408-slice-4_cell-20200408-sample-26_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-27_slice-20200408-slice-4_cell-20200408-sample-27_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-28_slice-20200408-slice-4_cell-20200408-sample-28_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-2_slice-20200408-slice-1_cell-20200408-sample-2_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-3_slice-20200408-slice-1_cell-20200408-sample-3_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-4_slice-20200408-slice-2_cell-20200408-sample-4_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-5_slice-20200408-slice-2_cell-20200408-sample-5_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-6_slice-20200408-slice-2_cell-20200408-sample-6_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-7_slice-20200408-slice-2_cell-20200408-sample-7_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-8_slice-20200408-slice-3_cell-20200408-sample-8_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

sub-mouse-ZUDOB/sub-mouse-ZUDOB_ses-20200408-sample-9_slice-20200408-slice-3_cell-20200408-sample-9_icephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 73, in main
    AssetMeta(**metadata)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AssetMeta
identifier
  field required (type=value_error.missing)

